os: osx
language: swift
osx_image: xcode10.1
xcode_workspace: "EP Calipers.xcworkspace"
xcode_scheme: "EP Calipers"
xcode_destination: platform=macOS
before_install:
  - gem install cocoapods --pre
  - pod install --repo-update
