os: osx
language: swift
osx_image: xcode10.2
before_install:
  - gem install cocoapods --pre
  - pod install --repo-update
script:
  # - KEY_CHAIN=ios-build.keychain
  # - security create-keychain -p travis $KEY_CHAIN
  # - security default-keychain -s $KEY_CHAIN
  # - security unlock-keychain -p travis $KEY_CHAIN
  # - security set-keychain-settings -t 3600 -u $KEY_CHAIN
  - xcodebuild -workspace EP\ Calipers.xcworkspace -scheme EP\ Calipers -destination platform\=macOS build test CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO

