os: osx
language: swift
# osx_image: xcode10.1
before_install:
  - gem install cocoapods --pre
  - pod install --repo-update
script: xcodebuild -workspace EP\ Calipers.xcworkspace -scheme EP\ Calipers -destination platform\=macOS build test CODE_SIGNING_REQUIRED=NO

